import streamlit as st
import pickle
import pandas as pd
import numpy as np

# ==========================
# Page Configuration
# ==========================

st.set_page_config(
    page_title="AI Disease Prediction System",
    page_icon="🩺",
    layout="centered"
)

# ==========================
# Load Files
# ==========================

model = pickle.load(open("model.pkl", "rb"))
symptom_index = pickle.load(open("symptom_index.pkl", "rb"))

description_df = pd.read_csv("symptom_Description.csv")
precaution_df = pd.read_csv("symptom_precaution.csv")

# ==========================
# Sidebar
# ==========================

st.sidebar.title("ℹ About Project")

st.sidebar.info("""
AI Disease Prediction System

Built Using:

• Python
• Pandas
• NumPy
• Scikit-Learn
• Random Forest
• Streamlit

Developer:
Krishna Yadav
""")

# ==========================
# Main Title
# ==========================

st.title("🩺 AI Disease Prediction System")

st.write(
    "Select symptoms and predict the most likely disease using Machine Learning."
)

# ==========================
# Symptom Selection
# ==========================

all_symptoms = sorted(list(symptom_index.keys()))

selected_symptoms = st.multiselect(
    "Select Symptoms",
    all_symptoms
)

# ==========================
# Prediction Button
# ==========================

if st.button("🔍 Predict Disease"):

    if len(selected_symptoms) == 0:

        st.warning(
            "Please select at least one symptom."
        )

    else:

        # Create Input Vector

        input_vector = [0] * len(symptom_index)

        for symptom in selected_symptoms:
            if symptom in symptom_index:
                input_vector[
                    symptom_index[symptom]
                ] = 1

        # Prediction

        prediction = model.predict(
            [input_vector]
        )

        disease = prediction[0]

        # ==========================
        # Confidence Score
        # ==========================

        confidence = None

        try:
            probabilities = model.predict_proba(
                [input_vector]
            )

            confidence = (
                np.max(probabilities[0]) * 100
            )

        except:
            pass

        # ==========================
        # Predicted Disease
        # ==========================

        st.success(
            f"Predicted Disease: {disease}"
        )

        if confidence is not None:

            st.info(
                f"Confidence Score: {confidence:.2f}%"
            )

        # ==========================
        # Top 3 Predictions
        # ==========================

        try:

            st.subheader(
                "🏆 Top 3 Possible Diseases"
            )

            top3_idx = np.argsort(
                probabilities[0]
            )[-3:][::-1]

            for idx in top3_idx:

                st.write(
                    f"• {model.classes_[idx]} "
                    f"({probabilities[0][idx]*100:.2f}%)"
                )

        except:
            pass

        # ==========================
        # Disease Description
        # ==========================

        st.subheader(
            "📖 Disease Description"
        )

        description_row = description_df[
            description_df["Disease"] == disease
        ]

        if not description_row.empty:

            description_column = (
                description_row.columns[1]
            )

            st.info(
                description_row.iloc[0][
                    description_column
                ]
            )

        else:

            st.write(
                "Description not available."
            )

        # ==========================
        # Precautions
        # ==========================

        st.subheader(
            "🛡 Recommended Precautions"
        )

        precaution_row = precaution_df[
            precaution_df["Disease"] == disease
        ]

        if not precaution_row.empty:

            for col in precaution_row.columns[1:]:

                value = precaution_row.iloc[0][col]

                if pd.notna(value):

                    st.write(
                        f"✅ {value}"
                    )

        else:

            st.write(
                "Precautions not available."
            )

# ==========================
# Footer
# ==========================

st.markdown("---")

st.caption(
    "⚠ This prediction is generated by a Machine Learning model and should not be considered medical advice."
)